version: "3.9"

services: 
  nginx:
    ports:
      - "3003:3003"
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs



